apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: runoncedurationoverrideoperator.v1.4.1
  namespace: openshift-run-once-duration-override-operator
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  annotations:
    alm-examples: |
      [
        {
          "apiVersion": "operator.openshift.io/v1",
          "kind": "RunOnceDurationOverride",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            "managementState": "Managed",
            "runOnceDurationOverride": {
              "spec": {
                "activeDeadlineSeconds": 3600
              }
            }
          }
        }
      ]
    certifiedLevel: "false"
    containerImage: registry-proxy.engineering.redhat.com/rh-osbs/run-once-duration-override-rhel9-operator:latest
    createdAt: "2026-04-23"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    olm.skipRange: ">=1.3.0 <1.4.1"
    description: An operator to manage the OpenShift RunOnceDurationOverride Mutating Admission Webhook Server
    repository: https://github.com/openshift/run-once-duration-override-operator
    support: Red Hat, Inc.
    capabilities: Basic Install
    categories: OpenShift Optional
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
    operatorframework.io/suggested-namespace: "openshift-run-once-duration-override-operator"
spec:
  replaces: runoncedurationoverrideoperator.v1.3.0
  # buffering up to 6 1.1.z releases to allow to include these in all supported bundle index images
  # The buffer len 6 should be sufficient for normal cadance. Including CVE releases.
  # The buffer can be extened later as needed.
  skips:
    - runoncedurationoverrideoperator.v1.2.0
    - runoncedurationoverrideoperator.v1.2.1
    - runoncedurationoverrideoperator.v1.2.2
    - runoncedurationoverrideoperator.v1.2.3
    - runoncedurationoverrideoperator.v1.2.4
    - runoncedurationoverrideoperator.v1.2.5
    - runoncedurationoverrideoperator.v1.2.6
    - runoncedurationoverrideoperator.v1.3.0
    - runoncedurationoverrideoperator.v1.3.1
    - runoncedurationoverrideoperator.v1.3.2
    - runoncedurationoverrideoperator.v1.3.3
    - runoncedurationoverrideoperator.v1.3.4
    - runoncedurationoverrideoperator.v1.3.5
    - runoncedurationoverrideoperator.v1.3.6
    - runoncedurationoverrideoperator.v1.4.0
  customresourcedefinitions:
    owned:
      - displayName: Run Once Duration Override
        description: RunOnceDurationOverride is the schema for the runoncedurationoverrides API
        group: operator.openshift.io
        kind: RunOnceDurationOverride
        name: runoncedurationoverrides.operator.openshift.io
        version: v1
  description: ""
  displayName: Run Once Duration Override Operator
  keywords: ["mutating", "webhook", "workload", "run-once"]
  provider:
    name: Red Hat, Inc.
  maturity: beta
  version: 1.4.1
  relatedImages:
    - name: run-once-duration-override-operand
      image: registry-proxy.engineering.redhat.com/rh-osbs/run-once-duration-override-rhel-9:latest
    - name: run-once-duration-override-operator
      image: registry-proxy.engineering.redhat.com/rh-osbs/run-once-duration-override-rhel9-operator:latest
  links:
    - name: Source Code
      url: https://github.com/openshift/run-once-duration-override
    - name: Source Code
      url: https://github.com/openshift/run-once-duration-override-operator
  maintainers:
    - email: support@redhat.com
      name: Red Hat
  minKubeVersion: 1.34.0
  labels:
    olm-owner-enterprise-app: run-once-duration-override-operator
    olm-status-descriptors: run-once-duration-override-operator.v1.4.1
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - rules:
            # to have the power to create 'RoleBinding' that refs extension-apiserver-authentication-reader
            # in kube-system namespace.
            # to give the operand power to read the config for terminating authentication.
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
              verbs:
                - create
                - update
                - patch
                - get
            # Operator must have these privs so that it can grant them to the operand
            - apiGroups:
                - flowcontrol.apiserver.k8s.io
              resources:
                - flowschemas
                - prioritylevelconfigurations
              verbs:
                - get
                - list
                - watch
            # to have the power to read configmaps in the kube-system namespace
            - apiGroups:
                - ''
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
            # to have the power to read cluster configuration for config observation
            - apiGroups:
                - config.openshift.io
              resources:
                - apiservers
              verbs:
                - get
                - list
                - watch
            # to have the power to ensure RBAC for the operand
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
                - clusterrolebindings
              verbs:
                - create
                - update
                - patch
                - get
            # to have the power to reconcile request(s)
            - apiGroups:
                - operator.openshift.io
              resources:
                - runoncedurationoverrides
                - runoncedurationoverrides/status
                - runoncedurationoverrides/finalizers
              verbs:
                - update
                - patch
                - get
                - list
                - watch
            # to have the power to manage configuration for admission webhook
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - mutatingwebhookconfigurations
              verbs:
                - create
                - update
                - patch
                - delete
                - list
                - watch
            # to have the power to manage APIService object(s)
            - apiGroups:
                - apiregistration.k8s.io
              resources:
                - apiservices
              verbs:
                - create
                - update
                - patch
                - get
                - list
                - watch
            # to grant the operand power to create admission reviews
            - apiGroups:
                - operator.openshift.io
              resources:
                - runoncedurationoverrides
              verbs:
                - create
            # default for an aggregated apiserver
            - apiGroups:
                - admissionregistration.k8s.io
              resources:
                - validatingwebhookconfigurations
                - mutatingwebhookconfigurations
              verbs:
                - get
                - list
                - watch
            # to grant power to the operand to watch Namespace(s)
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
                - list
                - watch
            # to grant power to the operand to delegate authentication and authorization
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
            # to grant power to the operand to use hostnetwork-v2 scc
            - apiGroups:
                - security.openshift.io
              resources:
                - securitycontextconstraints
              verbs:
                - use
              resourceNames:
                - hostnetwork-v2
            # to grant power to the operand to allow anonymous access to the admission server
            - apiGroups:
                - admission.runoncedurationoverride.openshift.io
              resources:
                - runoncedurationoverrides
              verbs:
                - create
                - get
          serviceAccountName: run-once-duration-override-operator
      permissions:
        - rules:
            # to have the power to ensure RBAC for the operand
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - create
                - update
                - patch
                - get
            # to have the power to watch secondary resources
            - apiGroups:
                - ''
              resources:
                - configmaps
                - secrets
                - services
                - serviceaccounts
                - pods
              verbs:
                - get
                - create
                - update
                - patch
                - list
                - watch
            # to have the power to create events
            - apiGroups:
                - ''
              resources:
                - events
              verbs:
                - create
                - update
                - patch
            # to have the power to watch secondary resources
            - apiGroups:
                - apps
              resources:
                - daemonsets
                - deployments
              verbs:
                - create
                - get
                - update
                - patch
                - list
                - watch
            # to have the power to manage leader election leases
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - create
                - get
                - update
                - patch
                - list
                - watch
          serviceAccountName: run-once-duration-override-operator
      deployments:
      - name: run-once-duration-override-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              runoncedurationoverride.operator: "true"
          template:
            metadata:
              name: runoncedurationoverride
              annotations:
                openshift.io/required-scc: restricted-v2
              labels:
                runoncedurationoverride.operator: "true"
              spec:
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                containers:
                  - name: run-once-duration-override-operator
                    terminationMessagePolicy: FallbackToLogsOnError
                    securityContext:
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      capabilities:
                        drop:
                          - ALL
                    image: registry-proxy.engineering.redhat.com/rh-osbs/run-once-duration-override-rhel9-operator:latest
                    command:
                      - /usr/bin/run-once-duration-override-operator
                    args:
                      - "start"
                      - "--namespace=$(OPERAND_NAMESPACE)"
                      - "--v=2"
                    imagePullPolicy: Always
                    env:
                      - name: OPERATOR_POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERAND_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: RELATED_IMAGE_OPERAND_IMAGE
                        value: registry-proxy.engineering.redhat.com/rh-osbs/run-once-duration-override-rhel-9:latest
                      - name: OPERAND_VERSION
                        value: 1.4.1
                    ports:
                      - containerPort: 8080
                    readinessProbe:
                      httpGet:
                        path: /healthz
                        port: 8080
                      initialDelaySeconds: 10
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8080
                      initialDelaySeconds: 5
                    volumeMounts:
                      - name: tmp
                        mountPath: "/tmp"
                serviceAccountName: run-once-duration-override-operator
                volumes:
                  - name: tmp
                    emptyDir: {}
